#! /bin/sh

mkdir -p /tmp/composer-cache
tty=false
tty -s && tty=true
docker run \
    --tty="$tty" \
    --interactive \
    --rm \
    --user "$(id -u):$(id -g)" \
    --volume /etc/passwd:/etc/passwd:ro \
    --volume /etc/group:/etc/group:ro \
    --volume /tmp/composer-cache:/tmp \
    --volume "$PWD:/app" \
    composer "$@"
